__name__ = 'remotelogin'
__description__ = 'Set of Libraries to Help with Device Automation Tasks.'
__url__ = ''
__version__ = '0.89.2'
__author__ = 'Filinto Duran'
__email__ = 'duranto@gmail.com'
__license__ = 'MIT'
__copyright__ = 'Copyright 2018 Filinto Duran'
