---
# example of deviceconn_settings file

vars: {}

db: {
     # vendor: ''
     # host: ''
     # port: ''
     # service_name:
     # db: ''
   }

connections: {
    # from remotelogin.connections.settings

    # SOCKET_TIMEOUT: 30
    # SOCKET_TIMEOUT_FOR_LOGIN: 8
    # SOCKET_TIMEOUT_FOR_LOGIN_TELNET: 8
    # SOCKET_KEEPALIVE_PERIOD: 0
    # TIMEOUT_FOR_PROMPT: 0.6
    # BUFFER_SIZE: 4096          # socket buffer size
    # SOCKET_TIME_SLEEP_SELECT: 0.5
    # CONNECTION_LOCAL_TIMEOUT: 0.1
    # CONNECTION_LOGIN_LOCAL_TIMEOUT: 0.25
    # TIMEOUT_FOR_EXEC_OUTPUT: 0.5
    # TIMEOUT_FOR_EXPECT: 0      # time to wait for the whole expected list to complete
    # SHELL_COLS: 16000            # interactive shell width
    # SHELL_ROWS:  3000         # interactive shell height
    # IANA_CSV_FILE: os.path.join(os.path.split(os.path.abspath(__file__))[0], 'service-names-port-numbers.csv')
    # KEEP_CONNECTIONS_DB: True
    # HIDDEN_DATA_MSG: 'PROTECTED/HIDDEN DATA'
    # BUFFER_SIZE_TO_RETURN_WHEN_ERROR = 200
  }

devices: {
    # from remotelogin.devices.settings

    # DEFAULT_STORAGE_FOLDER: 'c:\Users\my user'
    # ENCRYPT_PASSWORDS_IN_DB: False
    # LOCATION: ''
    }

vault: {
    # from remotelogin.utils.crypto.SecuredTextEngine.__init__

    # password_file: ''
    # password_script: ''
    # prompt_for_password: No
    # salt_file: ''
    }

selenium: {
    # from remotelogin.utils.selenium_utils.settings.py

    # WEB_DRIVER_EXECUTABLES_PATH: ''
    # REMOTE_PORT: 4444
    # MAX_LENGTH_FUNCTION_NAME_TO_RECORD = 40
    # WEB_DRIVER_EXECUTABLES_PATH = os.environ.get('SELENIUM_DRIVERS_PATH', 'selenium_drivers')
    # IMPLICIT_WAIT = 10
    # THINK_TIME = 0.5
    # SCREEN_SHOTS_FOLDER = 'selenium_shots'
    # DOWNLOAD_FOLDER = os.path.join(os.path.expanduser("~"), 'seleniumutils_downloads')
    # HIGHLIGHTING_COLOR = 'orange'
    # HIGHLIGHTING_SIZE = 4
    # ENABLE_SCREENSHOT_HIGHTLIGHTING = No
    # ENABLE_HIGHTLIGHTING = No
    # HEADLESS: No
    # HEADLESS_DISPLAY_WIDTH: 1024
    # HEADLESS_DISPLAY_HEIGHT: 768
    }

crypto: {
    # any of from cryptography.hazmat.primitives
    # DEFAULT_HASH_ALGORITHM_NAME: SHA256
}